name: "Hello .NET"

on:
  workflow_dispatch:

env:
  NOTES_API: Notes.Api.Test/Notes.Api.Test.csproj
  TEST_RESULT: Notes.Api.Test/TestResults/*.trx

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: "Print .NET CLI version"
        run: dotnet --version

      - name: "Restore"
        run: dotnet restore $NOTES_API

      - name: "Build"
        run: dotnet build --no-restore --configuration Release $NOTES_API

      - name: "Test"
        run: dotnet test --no-build --configuration Release --verbosity normal --logger trx $NOTES_API

      - name: "Report Tests"
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-report
          path: Notes.Api.Test/TestResults/*.trx
          reporter: dotnet-trx