name: "Hello .NET"

on:
  workflow_dispatch:

env:
  Notes.Api: Notes.Api.Test/Notes.Api.Test.csproj

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: "Print .NET CLI version"
        run: dotnet --version

      - name: "Restore"
        run: dotnet restore $Notes.Api

      - name: "Build"
        run: dotnet build --no-restore --configuration Release $Notes.Api

      - name: "Test"
        run: dotnet test --no-build --configuration Release --verbosity normal --logger trx $Notes.Api